# Generated by Django 5.0.6 on 2024-06-24 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0010_rename_review_review_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onyx_audio', models.FileField(blank=True, null=True, upload_to='onyx/')),
                ('nova_audio', models.FileField(blank=True, null=True, upload_to='nova/')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
