# Generated by Django 5.0.6 on 2024-06-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_rating_book_remove_rating_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='book',
            name='totalratings',
            field=models.IntegerField(default=0),
        ),
    ]
