# Generated by Django 5.0.6 on 2024-06-20 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_review_rating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('user', 'book', 'shelf_type')},
        ),
    ]
