# Generated by Django 5.0.6 on 2024-06-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_penalty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
