# Generated by Django 5.0.6 on 2024-06-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_delete_penalty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='content',
        ),
    ]
