# Generated by Django 5.0.6 on 2024-06-20 19:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_avatar.webp', null=True, upload_to=accounts.models.user_avatar_path),
        ),
    ]
